### ISSUE TITLE
CreateEffect doesn't react when object in store changes a parameter type from array to object and vice-versa

### ISSUE THREAD

**Issue by JaielZeus** [solidjs/solid#1831] opened 2023-07-29 12:36 UTC
### Describe the bug

When creating a store and subscribing via an effect to any change in the store, a simple change of a top-level value from array to object or vice-versa does not trigger the effect.

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

```JS
import { createEffect } from 'solid-js';
import {  createStore } from 'solid-js/store';

const [get, set] = createStore({ key: [] });

createEffect(() => {
    if ({ ...get }) {
      console.log('Something changed in get');
      console.log(JSON.stringify(get));
    }
  });

setInterval(() => {
    set('key', { time: Date.now() });
  }, 1000);
```

This is true for any depth the property I want to change from array to object is in. The crucial part is that here:

```JS
const [get, set] = createStore({ key: [] });
```

The property ``key`` is an array. 

On the other hand setting it to an object initially will trigger the effect though.
```JS
const [get, set] = createStore({ key: {} });
```

Additional proof:

Arbitrary depth also does not trigger the effect:

```JS
import { createEffect } from 'solid-js';
import {  createStore } from 'solid-js/store';

const [get, set] = createStore({ key1: { key2: { key3: { key4: [] } } } });

createEffect(() => {
    if ({ ...get }) {
      console.log('Something changed in get');
      console.log(JSON.stringify(get));
    }
  });

setInterval(() => {
    set('key1', 'key2', 'key3', 'key4', { time: Date.now() });
  }, 1000);
```

### Expected behavior

I expect the effect to trigger every second.

### Platform

- OS: Window
- Version: latest

### Additional context

The effect is not triggered by the simple ``{ ...get }`` destructuring I do in the effect. 
But imo it should trigger it, unless I did not read the docs correctly or overlooked some hidden "caveats" section with the reactivity system.

Please confirm wether I am wrong or not on this one!

### Edit:
 I also subscribed to the value directly without destructuring and it still does not trigger the effect unless the intital type for ``key`` is object and not array when overwriting it with an object:

```JS

import { createEffect } from 'solid-js';
import {  createStore } from 'solid-js/store';

const [get, set] = createStore({ key: [] });

createEffect(() => {
    if (get.key !== undefined) {
      console.log('Something changed in get');
      console.log(JSON.stringify(get));
    }
  });

setInterval(() => {
    set('key', { time: Date.now() });
  }, 1000);
```

**Comment by thetarnav** [comment] 2023-07-29 15:40
The issue is that the array is not getting changed by the date, but rather a property `"time"` is getting added and then updated in the array, as top level objects gets merged with the existing ones.
If you update the store like this it will trigger the update, as the array gets actually replaced:
```ts
//     v - updated property
//     v       v - updated property
//     v       v      v - new object
set('key', { time: Date.now() })

//     v - updated property
//     v       v - new object
set({ key: { time: Date.now() } })
```
https://playground.solidjs.com/anonymous/14d88fac-018d-44fc-b61b-375a3e2dafef

it may still be considered a bug if you expect the object to not be merged if the exiting object is an array

Although this will work fine, so the issue is just that `JSON.stringify()` doesn't iterate over non-number keys on arrays, so the new property gets ignored.
```ts
const [get, set] = createStore({ key: [] })

set("key", "time", Date.now())
````
https://playground.solidjs.com/anonymous/28c4f1e4-1ccf-4a5a-b4f4-85f6422fffd9

**Comment by JaielZeus** [comment] 2023-07-29 16:14
@thetarnav  This is just broken imo. Your first playground example is fine. You are replacing the store with a totally new object so I expect a change/it working like expected. But the second you presented shows even more that ther eis something broken because now your store is not reactive anymore because the get or get.key cannot be used in any form anymore and be reactive. get.key is for ever now an empty array seemingly but get.key.time is still retrievung the time property from that supposedly empty array. 

I think this is a huge caveat with the reactivity system

**Comment by ryansolid** [comment] 2023-07-31 18:45
So I understand. Are you expecting it to be an object at the end?

If you expect it to be an object then this is a matter of not using the right syntax. Objects merge in `setStore` so it would continue to be an array. In @thetarnav's example he's not actually replacing the store with a new object. He's merging "key" field into the top-level store which replaces the array with the object. This might not seem obvious but we mention it in the [docs](https://www.solidjs.com/docs/latest/api#updating-stores), and its legacy goes back to `setState` in React class components where it merges on keys rather than replaces the object. We kept this consistent throughout because it reduces the amount of code on multifield updates without resorting to cloning objects (and less granular updates)

You can see in this example `otherKey` never goes away: https://playground.solidjs.com/anonymous/edcf09cd-9d4c-4d39-aff4-0a02b9306be4

What is happening in your example is more like:
```js
const store = { key: [] }
store.key.time = Date.now();
JSON.stringify(store);
```
If you run this code you will see what I mean. It isn't that anything loses reactivity. But that JSON.stringify just shows the empty array because it is still an empty array that just happens to have a property on it that JSON.stringify doesn't look at.

Where as in the example I shared above(and in @thetarnav first example) it is more like:
```js
const store = { key: [], otherKey: "hi" }
store.key = { time: Date.now() }
JSON.stringify(store);
```

I guess the question is, if we detect someone setting a key on an array should we assume it can't be merged and should just replace with a new object? My gut is probably no because you could want to listen to a property on said array. I think if we changed it to behave that way it would be unexpected to those who know the API merges. That being said this is a prime example for why the `produce` interface seems preferable as the default in future versions of Solid Stores.

**Comment by JaielZeus** [comment] 2023-08-03 19:41
I know JS is weird with how arrays are handeled compared to other languages as they are some type of objects. Well let's call this an edge case then and if you run into it, it is your problem because your design choices might be questionable. You just have to keep in mind then if you decide to store data as an array in the store you cannot get rid of it being an arrays and same applies to objects unless you overwrite with a new reference in such a way that it is not merged.

@ryansolid I think a mutable approach to stores should be the way to go in the future too if it doesn't sacrifice too much on the performance side.

**Comment by ryansolid** [comment] 2023-08-09 18:10
> You just have to keep in mind then if you decide to store data as an array in the store you cannot get rid of it being an arrays and same applies to objects unless you overwrite with a new reference in such a way that it is not merged.

It's not so much an edge case as an API that has a defined behavior that some might not expect. Everything you wish to accomplish is expressible with the correct syntax. It isn't obvious but once you know it isn't an issue and it is consistent. Only top objects merge and this makes sense in that top level it has to merge unless it diffs as stores are a reference you can't replace. 

> @ryansolid I think a mutable approach to stores should be the way to go in the future too if it doesn't sacrifice too much on the performance side.

It isn't so much performance as it can be dangerous to pass around mutable reactive objects. We've lived in an immutable world so long with React and VDOMs it sometimes isn't as obvious, but back before then passable mutability was a surefire way to cause all sorts of data flow messes. I see the benefit in providing a mutable interface but it will still be guarded so that the ability to mutate isn't implicit from just passing the store down.

**Closed** 2023-08-09 18:11 UTC
