### ISSUE TITLE
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node #8

### ISSUE THREAD

**Issue by wakaztahir** [solidjs/solid#1898] opened 2023-10-05 11:54 UTC
### Describe the bug

Here's a reproducer
https://github.com/Qawaz/solid-start-issue

In the reproducer I've made two success samples demonstrating the same library succeeding with a little source code modification even when both source code samples are correct, This is an error with solidjs itself.

You'll notice that If you put text or any element above the errored component the error goes away, I've demonstrated that using a success file.

The error only occurs in ssr mode

### Your Example Website or App

https://github.com/Qawaz/solid-start-issue

### Steps to Reproduce the Bug or Issue

`yarn install` the repo
`yarn run start` the repo
navigate to `error` page
refresh the page -> ERROR

### Expected behavior

The error should not occur with the library source code

### Platform

- OS: [e.g. Windows 11]
- Browser: [e.g. Chrome]

**Comment by ryansolid** [comment] 2023-10-09 20:21
Looks like this one will be fixed by another issue I fixed in 1.8.

**Closed** 2023-10-09 22:54 UTC
Labels: bug

**Comment by pyoung-o** [comment] 2024-01-29 23:39
I'm seeing this error (flakily) with solid-js versions 1.8.4->1.8.12

Was previously using 1.8.1 and did not see the error, however we also upgraded vite and solid-start so downgrading solid-js below 1.8.4 is giving a different error.

Any idea if maybe there was a regression somewhere between 1.8.1 and 1.8.4 that's causing this error?

**Comment by anthonyborell** [comment] 2024-04-05 03:30
Am having this same problem using SortableJS and solid. Would be worth reopening.

**Comment by Blankeos** [comment] 2025-01-03 09:27
@jackkingham-au this happens to me as well! Have you figured out anything on why this happens?
I'm using
```
    "solid-js": "^1.9.3",
    "sortablejs": "^1.15.6",
```

**Comment by kachurun** [comment] 2025-02-08 02:10
Why its closed guys? Have the same bug as mentioned above in same situation with SortableJS

**Comment by kachurun** [comment] 2025-02-08 02:44
Hm, `reconcile` fixing this behaviour

```
...
        const sortable = new Sortable(listEl(), {
            group: `sortable-${ createUniqueId() }`,
            ...defaultOptions,
            ...sortableOptions,
            
            onStart: (evt: SortableEvent) => {
                if (items && evt.oldIndex !== null) {
                    dragStore.setItem(items[evt.oldIndex]);
                }

                sortableOptions.onStart?.(evt);
            },
                
            onEnd: (evt: SortableEvent) => {
                dragStore.setItem(null);
                sortableOptions.onEnd?.(evt);
                    
                // Handle reordering within the same list
                if (items && setItems && evt.from === evt.to && evt.oldIndex !== null && evt.newIndex !== null) {
                    const newItems = [...items];
                    const [movedItem] = newItems.splice(evt.oldIndex, 1);
                    newItems.splice(evt.newIndex!, 0, movedItem);

                    setItems(reconcile(newItems));
                }
            },
                
            onAdd: (evt: SortableEvent) => {
                sortableOptions.onAdd?.(evt);

                if (items && setItems && evt.newIndex !== null && dragStore.item) {
                    const newItems = [...items];
                    newItems.splice(evt.newIndex!, 0, dragStore.item);

                    setItems(reconcile(newItems));
                }
            },
                
            onRemove: (evt: SortableEvent) => {
                sortableOptions.onRemove?.(evt);

                if (items && setItems && evt.oldIndex !== null) {
                    const newItems = [...items];
                    newItems.splice(evt.oldIndex!, 1);
                        
                    setItems(reconcile(newItems));
                }
            }
        });
...
```

**Comment by telephant** [comment] 2025-04-04 07:27
> Hm, `reconcile` fixing this behaviour
> 
> ```
> ...
>         const sortable = new Sortable(listEl(), {
>             group: `sortable-${ createUniqueId() }`,
>             ...defaultOptions,
>             ...sortableOptions,
>             
>             onStart: (evt: SortableEvent) => {
>                 if (items && evt.oldIndex !== null) {
>                     dragStore.setItem(items[evt.oldIndex]);
>                 }
> 
>                 sortableOptions.onStart?.(evt);
>             },
>                 
>             onEnd: (evt: SortableEvent) => {
>                 dragStore.setItem(null);
>                 sortableOptions.onEnd?.(evt);
>                     
>                 // Handle reordering within the same list
>                 if (items && setItems && evt.from === evt.to && evt.oldIndex !== null && evt.newIndex !== null) {
>                     const newItems = [...items];
>                     const [movedItem] = newItems.splice(evt.oldIndex, 1);
>                     newItems.splice(evt.newIndex!, 0, movedItem);
> 
>                     setItems(reconcile(newItems));
>                 }
>             },
>                 
>             onAdd: (evt: SortableEvent) => {
>                 sortableOptions.onAdd?.(evt);
> 
>                 if (items && setItems && evt.newIndex !== null && dragStore.item) {
>                     const newItems = [...items];
>                     newItems.splice(evt.newIndex!, 0, dragStore.item);
> 
>                     setItems(reconcile(newItems));
>                 }
>             },
>                 
>             onRemove: (evt: SortableEvent) => {
>                 sortableOptions.onRemove?.(evt);
> 
>                 if (items && setItems && evt.oldIndex !== null) {
>                     const newItems = [...items];
>                     newItems.splice(evt.oldIndex!, 1);
>                         
>                     setItems(reconcile(newItems));
>                 }
>             }
>         });
> ...
> ```

Hi, do you have complete code for this? I am facing the same issue and struggling.

**Comment by kachurun** [comment] 2025-04-07 01:09
> Hi, do you have complete code for this? I am facing the same issue and struggling.

I think it changed a bit since the last message. I’ve struggled with this and completely rewritten everything maybe 3 or 4 times.

```typescript
/// <reference types="solid-labels" />

import { Key } from '@solid-primitives/keyed';
import { Index, Show, batch, createEffect, createMemo, createSignal, createUniqueId, on, onCleanup, onMount } from 'solid-js';
import { Dynamic } from 'solid-js/web';

import { ForwardRef } from './ForwardRef';
import { Sortable, type Options as SortableOptions, type SortableEvent } from '@packages/sortable';

import type { JSX } from 'solid-js';

type Item = {
    id: string | number;
    [key: string]: any;
};

export type SortableListProps<T extends Item> = Partial<SortableOptions> & {
    ref?: (el: HTMLElement) => void;
    children: (item: Accessor<T>, index: Accessor<number>) => JSX.Element;
    fallback?: JSX.Element; // Empty list state

    // Don't render own wrapper element and bind sortable to the parentNode
    asChild?: boolean;     
    tag?: string;

    items?: T[];
    setItems?: (items: T[], oldItems: T[], evt?: SortableEvent) => void;

    // NOTE: For match selected with dom nodes they MUST have dataIdAttr is set
    selected?: (T['id'])[] | { has: (id: T['id']) => boolean } | ((item: T['id']) => boolean);
    class?: string;

    rerender?: boolean;
    
    // Sorting enabled
    enabled?: boolean;
    // Use Key instead of Index to render children
    keyedBy?: string;
};

// Simple store for the currently dragged items
let draggedItems = [] as any[];

const defaultOptions: Partial<SortableOptions> = {
    animation: 350,
    draggable: '[data-id]]',

    // NOTE: Attribute MUST be set to rendered elements to avoid issues with MultiDrag plugin
    dataIdAttr: 'data-id',
    revertOnSpill: false, // disable internal spill handling
    removeOnSpill: false, // disable internal spill handling
    revertOnEsc: true,
    
    shouldRevert: false, // Function to determine if an item should revert when spilled
    forceFallback: true,
    fallbackTolerance: 3,
    fallbackClass: 'field-list__sortable-ghost',
    dragClass: 'field-list__sortable-drag',
    chosenClass: 'field-list__sortable-chosen',
    ghostClass: 'field-list__sortable-placeholder',
};

export function SortableList<T extends Item>(props: SortableListProps<T>) {
    const { 
        tag = 'div',
        // Rerender the list after sorting
        // If false - return elements to their original positions in the DOM before setItems
        // If true - unmount the list before setItems and mount it again after it changes
        rerender = true,
        enabled = true,
        ref,
        items = [],
        setItems,
        class: className,
        selected = [],
        asChild,
        ...sortableOptions 
    } = $destructure(props);
    
    const [rendered, setRendered] = createSignal(true);
    const [listEl, setListEl] = createSignal<HTMLElement>();
    const [childrenEl, setChildrenEl] = createSignal<HTMLElement[]>([]);
    const [helper, setHelper] = createSignal<HTMLElement>();
    const [sortable, setSortable] = createSignal<Sortable>();
    
    const setListAndRef = (el: HTMLElement) => {
        setListEl(el);
        ref?.(el);
    };
    
    const selectedItems = createMemo(() => items.filter((item) => {
        if ('has' in selected) {
            return selected.has(item.id);
        }

        if (Array.isArray(selected)) {
            return selected.includes(item.id);
        }
        
        if (typeof selected === 'function') {
            return selected(item.id);
        }
    
        return false;
    }));
    
    const activeInstances = new Set<HTMLElement>();
    const sortableItems = new Set<HTMLElement>();
    
    createEffect(() => {
        if (!listEl() || !enabled) return;
        let originalOrder: HTMLElement[] = [];
        
        const options = {
            ...defaultOptions,
            ...sortableOptions,
        };
        
        const instance = new Sortable(listEl(), {
            group: `sortable-${ createUniqueId() }`,
            ...options,
            
            // Item choosen (but not dragged yet)
            onChoose: (evt: SortableEvent) => {
                originalOrder = Array.from(instance.el.children) as HTMLElement[];
                const n = originalOrder.length;
                
                // Normalize dataId attribute for each child element if not present
                for (let i = 0, j = 0; i < n; i++) {
                    const el = originalOrder[i];

                    if (instance.closest(el)) {
                        const id = String(items[j].id);
                        
                        if (!el.hasAttribute(options.dataIdAttr)) {
                            el.setAttribute(options.dataIdAttr, id);
                        }
                        
                        j += 1;
                    }
                }
                
                options.onChoose?.(evt);
            },
            
            // Item dragged a little
            onStart: (evt: SortableEvent) => {
                if (items) {
                    draggedItems = evt.indicies.map(
                        ({ id, oldIndex }) => items.find(item => item.id === id) || items[oldIndex]
                    ).filter(Boolean);
                }
                
                options.onStart?.(evt);
            },
            
            // Drop: Item added to the list
            onAdd: (evt: SortableEvent) => {
                // Return elements to their original positions in source list if not rerendering
                if (!rerender) {
                    const indicies = [...evt.indicies].sort((a, b) => b.oldIndex - a.oldIndex);

                    indicies.forEach(({ el, oldIndex }) => {
                        const sourceList = evt.from;
                        const referenceNode = Array.from(sourceList.children)[oldIndex];

                        if (referenceNode) {
                            sourceList.insertBefore(el, referenceNode);
                        }
                        else {
                            sourceList.appendChild(el);
                        }
                    });
                }
                
                batch(() => {
                    setRendered(false);
                    options.onAdd?.(evt);
                
                    if (items && setItems) {
                        const newItems = [...items];
                        const newIndex = Math.min(...evt.indicies.map(({ newIndex }) => newIndex));
                    
                        newItems.splice(newIndex, 0, ...draggedItems);
                    
                        setItems(newItems, items, evt);
                    }
                });
            },

            // Drop: Item removed from the list
            onRemove: (evt: SortableEvent) => {    
                batch(() => {
                    setRendered(false);
                    options.onRemove?.(evt);
                
                    const canRemove = evt.pullMode !== 'clone';

                    if (canRemove && items && setItems) {
                        const newItems = items.filter(
                            item => !draggedItems.some(dragItem => dragItem.id === item.id)
                        );
                    
                        setItems(newItems, items, evt);
                    }
                });
            },
            
            // Drop: Item dropped
            onEnd: (evt: SortableEvent) => {
                const isSorting = evt.from === evt.to;
                
                // Return element to its original position in the DOM to allow SolidJS to rerender the list properly
                if (isSorting && !rerender) {
                    const indicies = [...evt.indicies].sort((a, b) => b.oldIndex - a.oldIndex);

                    indicies.forEach(({ el, oldIndex, newIndex }) => {
                        if (oldIndex === newIndex) {
                            return;
                        }
                    
                        const sourceList = evt.from;
                    
                        if (sourceList) {
                            const referenceNode = originalOrder[oldIndex + 1];
                        
                            // Insert the element back to its original position
                            if (referenceNode) {
                                sourceList.insertBefore(el, referenceNode);
                            }
                            else {
                                sourceList.appendChild(el);
                            }
                        }
                    });
                }
                
                batch(() => {
                    setRendered(false);
                    options.onEnd?.(evt);

                    if (items && setItems && isSorting) {
                        const newItems = [...items];
                    
                        // Sort indices in descending order to avoid index shifting when splicing
                        const sortedIndices = [...(evt.indicies || [])].sort((a, b) => b.oldIndex - a.oldIndex).filter(({ oldIndex, newIndex }) => oldIndex !== newIndex);
                    
                        // First remove all items from their old positions
                        sortedIndices.forEach(({ oldIndex }) => {
                            newItems.splice(oldIndex, 1);
                        });
                    
                        // Then insert them at their new positions
                        sortedIndices
                            .sort((a, b) => a.newIndex - b.newIndex)
                            .forEach(({ id, newIndex }) => {
                                const item = items.find(item => String(item.id) === String(id));

                                if (item) {
                                    newItems.splice(newIndex, 0, item);
                                }
                            });
                    
                        setItems(newItems, items, evt);
                    }
                });

                draggedItems = [];
                originalOrder = [];
            },
        });

        setSortable(instance);

        onCleanup(() => {
            sortable()?.destroy();
            setSortable(null);
        });
    });

    // Effect to sync selected with MultiDrag state
    createEffect(() => {
        const el = listEl();
        const instance = sortable();
        const selectedIds = selectedItems().map(item => String(item.id));
        const nodes = childrenEl();

        if (!el || !instance || !rendered() || !nodes.length) {
            return;
        }

        // Find all dom nodes that match selected ids
        const elements = selectedIds.length ? nodes.filter(
            node => selectedIds.includes(
                node.getAttribute(sortableOptions.dataIdAttr || defaultOptions.dataIdAttr)
            )
        ) : [];

        // Deselect all items
        instance.multiDrag.resetSelected();
                    
        // Select filtered elements
        elements.forEach((element) => {
            instance.multiDrag.select(element); 
        });
    });

    // Immediately render the list after it was hidden
    createEffect(on(rendered, () => setRendered(true)));

    if (asChild) {
        onMount(() => {
            setListAndRef(helper()?.parentElement);
        });
    }
    
    const ListContent = () => (
        <Show when={ rerender ? rendered() : true }>
            <ForwardRef ref={ setChildrenEl }>
                { props.keyedBy ? (
                    <Key each={ items } by={ props.keyedBy } fallback={ props.fallback }>{ props.children }</Key>
                ) : (
                    <Index each={ items } fallback={ props.fallback }>
                        { (item: Accessor<T>, index: number) => props.children(item, () => index) }
                    </Index>
                ) }
            </ForwardRef>
        </Show>
    );
    
    return asChild ? (
        <>
            { /* Helper to determine list element (parent of this component) */ }
            { !listEl() && <div ref={ setHelper } /> }
            <ListContent />
        </>
    ) : (
        <Dynamic 
            component={ tag } 
            class={ className }
            ref={ setListAndRef }
        >
            <ListContent />
        </Dynamic>
    );
}
```

ForwardRef (or use @solid-primitives/refs instead):
```typescript
import { children, createEffect } from 'solid-js';
import type { JSX } from 'solid-js';

// Allows to get refs of children components, even if they lazy or not forwarded ref
export const ForwardRef = (props: { children: JSX.Element; ref: (value: JSX.Element[]) => void }) => {
    const kids = children(() => props.children);
    
    createEffect(() => {
        props.ref?.(kids.toArray().filter(e => e != null));
    });
    
    return (<>{ kids() }</>);
};

```

Couple of details here:

- You can pass the rerender option, which will completely remove all items before calling setItems (and any other events like onAdd/onRemove/onEnd) and render them again after the items from props change. Then your action will be completed, I guess. It works really well for relatively small lists and is reliable.

- If you’re not using the rerender option, it will revert any changes in the DOM before performing any callbacks, so it helps Solid not go crazy.

- Maybe you don't have evt.indicies in your sortable events—I'm not sure, but most probably it comes from my plugin for sortable, because my Sortable supports multi-item dragging. You can just replace the indices array with directly using oldIndex and newIndex, so your code will be simpler. For the same reason, just remove any multiDrag-related logic.

- I'm using @solid-primitives/keyed for list item memoization because I deal with relatively large lists with sorting/filtering and continuously changing items. You can replace it with a plain For.

- It supports working without a root element (asChild prop). In that case, it won’t create a wrapper for your items. If you don’t need that, then you don’t need ForwardRef, and you can make the code a lot simpler.


But in general, it works great in production with:
- Relatively large lists (5k–15k items)
- Multi-dragging
- Dragging between lists
