### ISSUE TITLE
JSX does not wait for transitions to complete when using a ternary in a prop value

### ISSUE THREAD

**Issue by Tonius** [solidjs/solid#2161] opened 2024-05-14 14:07 UTC
### Describe the bug

When using a ternary expression as part of a prop value in JSX, transitions do not seem to work properly. The DOM is updated immediately, instead of waiting until all resources in the transition are resolved.

When not using a ternary, or moving it to a derived signal outside of the JSX, the transition works correctly.

### Your Example Website or App

https://playground.solidjs.com/anonymous/f17b29b5-34f9-4cc5-af35-64c92380def3

### Steps to Reproduce the Bug or Issue

1. Click the 'Increment' button a few times to see how the rendered counts change.
2. Under 'Without ternary', the counts are updated in sync, and the transition works as intended.
3. Under 'With ternary', the counts are updated independently, without waiting for both resources to be resolved.

### Expected behavior

Under both 'Without ternary' and 'With ternary', the counts should wait for both resources to be resolved before updating the DOM.

### Platform

- OS: Linux (Arch)
- Browser: Firefox
- Version: 125.0.3

**Comment by ryansolid** [comment] 2024-05-14 18:00
This issue is probably a duplicate of: https://github.com/solidjs/solid/issues/1781

**Comment by Tonius** [comment] 2024-05-15 19:25
Solid 2.0 looks promising, from what I've seen it will bring many improvements in the async department.

So for now, it is better to avoid this pattern when reading resources that are part of a transition? Are there any other patterns to be aware of, that can have this problem?

**Comment by ryansolid** [comment] 2024-05-16 19:06
Yeah ternaries can be resolved inside out. It and boolean expressions are probably the only ones that apply that sort of optimization in the JSX that leads to that. They didn't always but I had changed it to fix another bug... the way we do normalization of insertion just needs to change in general.

**Comment by ryansolid** [comment] 2024-05-17 21:06
Anyway I'm going to track the single issue. Thanks for reporting and I'm looking forward to getting this more streamlined.

**Closed by ryansolid** 2024-05-17 21:06 UTC
