### ISSUE TITLE
generateHydrationScript not working

### ISSUE THREAD

**Issue by diogoparente** [solidjs/solid#830] opened 2022-02-04 19:00 UTC
**Describe the bug**
Hello there! I am trying make use of SolidJS's async SSR and `generateHydrationScript` does not seem to be working.

**To Reproduce**
1. The HTML has an `<esi>` tag that gets replaced with the HTML from the JSX below (which is working as intended) 🍾 

<details>
<summary>Code</summary>

- Page HTML

<img width="821" alt="Screenshot 2022-02-04 at 19 01 50" src="https://user-images.githubusercontent.com/66437099/152587631-7e3dc53c-d00b-4103-a5cf-5b6345f91149.png">

- JSX Component

<img width="545" alt="Screenshot 2022-02-04 at 18 50 51" src="https://user-images.githubusercontent.com/66437099/152586209-2f48d044-1ae5-4922-89d2-298a646734a8.png">

- Returned stringed HTML

<img width="486" alt="Screenshot 2022-02-04 at 18 51 01" src="https://user-images.githubusercontent.com/66437099/152586261-e3943207-19b6-44e5-8a82-cbfcbe2bb75f.png">

</details>

2. The page HTML <head> has an inline `generateHydrationScript()` to hydrate the new replaced HTML.

<details>
<summary>Code</summary>

<img width="321" alt="Screenshot 2022-02-04 at 18 52 01" src="https://user-images.githubusercontent.com/66437099/152586415-093436d9-e053-4ab0-8792-1893f5c4482d.png">

</details>

3. The HTML doesn't get hydrated.

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/66437099/152586811-7135768f-8522-4175-b8f8-8d39de5c91f6.mov

</details>

**Expected behavior**
The rendered HTML gets hydrated.

**Additional context**
When the page is loaded the HTML starts its life as an `<esi>` that eventually gets replaced with the SSR HTML.
Can this be the reason why the hydration doesn't work?

Thank you 🙏

**Comment by ryansolid** [comment] 2022-02-08 07:48
Poaaibly. What does the client side entry look like. Like what element are you calling `hydrate` on?

**Comment by diogoparente** [comment] 2022-02-09 09:46
Hey @ryansolid, thank you for spending your time on this 🙇‍♂️ 

My team is dropping this POC as we can't have an hydration step on the browser.

In summary we are just rendering a `<button>` that replaces the `<esi>` (the one on the first screenshot).
By the time it gets replaced, the `generateHydrationScript()` isn't making the `<button>` interactive, and it feels
like it's because the ssr `<button>` isn't present when the script runs.

Probably not the best library for this and therefor we're gonna try other things, but anyway I'm loving SolidJS
and looking forward to use it soon in some other opportunity!

Keep up the good work 💪

**Comment by ryansolid** [comment] 2022-02-09 15:31
Im just saying is the hydration script is like a global registry. I need more information like what the client entry looks like as you only shared the server code. If you want I can still look into this with more information or a simple reproduction. Otherwise feel free to close the issue.

**Comment by diogoparente** [comment] 2022-02-10 10:54
So, the hydration script is set on <head> and the entry should be the `<button data-hk="0.0" id="hello">Clicked 0 times.</button>`.

Below is my implementation:

<details>
<summary>HTML</summary>

<img width="722" alt="Screenshot 2022-02-10 at 10 51 40" src="https://user-images.githubusercontent.com/66437099/153392406-e519b781-93b6-4c96-a1b3-00c312c52285.png">

</details>

<details>
<summary>DOM with replaced ESI</summary>

<img width="722" alt="Screenshot 2022-02-10 at 10 51 40" src="https://user-images.githubusercontent.com/66437099/153392406-e519b781-93b6-4c96-a1b3-00c312c52285.png">

</details>

Maybe I'm doing something wrong here?

**Comment by ryansolid** [comment] 2022-02-16 07:07
Is there a client side entry bundle? There should be a bundle built with options `generate: "dom", hydratable: true` in babel preset, and it should open with a `hydrate` call on your app. I don't see a script tag for that. The hydration script is a global script to manage things before JS loads but we still need a client bundle.

**Comment by diogoparente** [comment] 2022-02-21 10:34
Thank you for your help @ryansolid, I'm dropping this investigation as my team is dealing with this in a different way.

**Closed** 2022-02-21 10:34 UTC
Labels: unverified bug
