### ISSUE TITLE
Cannot properly bind numbers to Select

### ISSUE THREAD

**Issue by marvin-j97** [solidjs/solid#2145] opened 2024-04-25 20:13 UTC
### Describe the bug

Creating a controlled Select does not seem to work with numbers. Using strings works fine.

### Your Example Website or App

https://playground.solidjs.com/anonymous/fa9dd633-0354-4a80-94fa-d308fdfa8e2e

### Steps to Reproduce the Bug or Issue

1. The value starts at 7, but the Select displays nothing
2. Select some value, the ev.currentTarget will be empty, so the value will be emitted as 0
3. Change <option> values to strings, and it will work as expected

### Expected behavior

Either it works or numbers are not allowed as Select values. Type is:

```
JSX.OptionHTMLAttributes<HTMLOptionElement>.value?: string | number | string[] | undefined
```

### Platform

- OS: Ubuntu
- Browser: Chrome, Firefox

**Comment by ryansolid** [comment] 2024-04-25 21:57
Duplicate of #2144.

Already fixed .. will be in the next release.

**Comment by LexSwed** [comment] 2024-06-25 08:04
@ryansolid was the fix released? I see the issue is still open and the Playground still shows the issue 👀

**Comment by ryansolid** [comment] 2024-06-25 15:19
Oh yeah I think you are right. I haven't done a Solid release recently. So this probably hasn't been released yet.

**Closed** 2024-06-27 20:18 UTC
Labels: compilation
