### ISSUE TITLE
computations created outside a `createRoot` or `render` will never be disposed

### ISSUE THREAD

**Issue by weijarz** [solidjs/solid#2130] opened 2024-04-15 12:25 UTC
### Describe the bug

The console prints this message in bulk:
```
computations created outside a `createRoot` or `render` will never be disposed
```

Full source:
```tsx
import { createStore } from 'solid-js/store'
import { render } from 'solid-js/web'

const is2024 = () => true

function Sub(props: { disabled: boolean }) {
  function onMouseMove() {
    if (props.disabled) console.log('disabled')
  }

  return (
    <div onMouseMove={onMouseMove}>
      <h1>Move your mouse here!</h1>
    </div>
  )
}

function Counter() {
  const [store, setStore] = createStore({ data: { count: 0 } })
  return (
    <>
      <Sub disabled={store.data.count > 0 && is2024()} />
    </>
  )
}

render(() => <Counter />, document.getElementById('app')!)
```

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-w6pnaq?file=src%2FApp.jsx

### Steps to Reproduce the Bug or Issue

The Browser Console prints a lot of messages ('computations created outside a `createRoot` or `render` will never be disposed') when the mouse is moved over the text, and the memory usage seems to be going up.

Change this line from
```
<Sub disabled={store.data.count > 0 && is2024()} />
```
to
```
<Sub disabled={store.data.count > 0} />
```
No more messages are printed after that.

### Expected behavior

Do not print warn messages.

### Platform

- OS: Linux
- Browser: Chrome/Firefox
- Version: 123

**Comment by atk** [comment] 2024-04-15 14:29
You are using a prop in an event. Since events and timeouts are run outside of the reactive scope, you get that message warning you that tracking is impossible, unless you use `untrack` to tell solid not to make the scope reactive in which this is run.

**Comment by ryansolid** [comment] 2024-04-15 16:52
When we changed the compilation of the conditional in component props we started seeing this as we create a short-lived memo on `props.disabled` access this is due to the heuristic not being able to tell if `is2024` is substantial work.

In any case this is a duplicate of: https://github.com/solidjs/solid/issues/1715

**Closed by ryansolid** 2024-04-15 16:52 UTC

**Comment by weijarz** [comment] 2024-04-16 01:51
Thanks, I understand.
It seems that the main problem is that accessing auto memorized attribute in the event handler function (which out of the normal execution context) may cause this problem.

Wrapping it in a function seems to prevent the property to auto create unwanted memo.
```ts
function noMemo(data) {  return data }

<Sub disabled={noMemo(store.data.count > 0 && is2024())} />
```
