### ISSUE TITLE
Hydration bug when signal is not wrapped in a DOM element

### ISSUE THREAD

**Issue by sebholstein** [solidjs/solid#1079] opened 2022-06-24 07:17 UTC
### Describe the bug

I used solid-start to write this simple counter component. In combination with hydration, the assignment to the dom element seems broken:

```tsx
import { createSignal } from "solid-js";

export default function Home() {
  const [count, setCount] = createSignal(0);
  return (
    <>
      {count()}
      <button type="button" onclick={() => setCount(count() + 1)}>
        up
      </button>
    </>
  );
}
```

When I click the button, the initial value of `0` stays visible on the page. Next to the `0`, a `1` gets displayed.

### Your Example Website or App

https://stackblitz.com/github/sebholstein/solid-hydration-demo?file=src/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. generate a solid-start project
2. add the described component to a page
3. run pnpm dev
4. click the button

### Expected behavior

The initial value of `0` should be gone after a first button click.

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 102

**Comment by ryansolid** [comment] 2022-06-25 01:52
Just viewing the stackblitz project you link it looks to be working correctly. I see the 0 become 1, 2, 3, as I click through it. 0 doesn't stay visible. Can you confirm?

**Comment by sebholstein** [comment] 2022-06-25 18:34
@ryansolid Sorry, provided the wrong example. Here is the correct project: https://stackblitz.com/github/sebholstein/solid-hydration-demo?file=src/routes/index.tsx

**Comment by ryansolid** [comment] 2022-06-26 02:45
Yeah pretty sure this is a duplicate of #1066. I will have a fix shortly.

**Closed** 2022-06-26 04:13 UTC
Labels: bug
