### ISSUE TITLE
Imported directive not defined (with TypeScript)

### ISSUE THREAD

**Issue by Ehesp** [solidjs/solid#1005] opened 2022-05-23 14:25 UTC
### Describe the bug

Working with directives and TypeScript doesn't seem to be playing well together.

When importing a directive from a file, I get the error:

```
ReferenceError: <name> is not defined
```

I came across this issue: https://github.com/solidjs/solid/issues/569

Adding my Vite plugin as:

```
solidPlugin({ typescript: { onlyRemoveTypeImports: true } }),
```

then causes another issue: `The requested module '/node_modules/.vite/deps/solid-js.js?v=dacde466' does not provide an export named 'Component'`

### Your Example Website or App

https://stackblitz.com/edit/solid-vite-sv6hn7?file=src/index.tsx

### Steps to Reproduce the Bug or Issue

1. Make a file for your directive.
2. Import it and attach it.
3. Open the console to see the error.

### Expected behavior

The directive is recognised.

### Platform

- OS: macOs
- Browser: Chrome
- Version: 101.0.4951.64

### Additional context

TypeScript also complains about:

```
'useFoo' is declared but its value is never read. ts(6133)
```

**Comment by atk** [comment] 2022-05-23 14:52
Duplicate of https://github.com/solidjs/solid/issues/569

**Comment by edemaine** [comment] 2022-05-23 17:18
See also [this section of the TypeScript guide](https://www.solidjs.com/guides/typescript#use%3A___).

**Comment by snnsnn** [comment] 2022-05-24 03:30
I think using the directive inside the components body will save it from getting tree shaken:

```typescript
function Counter() {
  useFoo;
  return <button use:useFoo>Hello!</button>;
}
```

**Comment by elite174** [comment] 2022-05-25 13:22
Would it be better to improve directives syntax instead?
Some time ago solid supported `className` field. It means that it's possible to make a solid field called `use={[directivesArrayHere]}`. IMO this would be more straightforward and obvious. Moreover it will eliminate issue with typescript (actually, these typescript guides for using directives sound like a hack)

**Comment by Ehesp** [comment] 2022-05-27 18:03
I agree with that. I'm really liking working with directives but it does feel a bit hacky having to declare the variables randomly.

**Comment by ryansolid** [comment] 2022-05-28 02:52
Yeah it's super unfortunate. But if you ignore TS the current syntax makes a lot of sense and is "better". I went into detail about this in some older issue when we first introduced this. These same suggestions came up at the time although it wasn't for this tree shaking problem. I'd be all for some solution to do this with compilation. Like some ability to change the file before TS gets it, but I don't want to change the existing syntax if possible.

**Comment by elite174** [comment] 2022-05-29 16:27
Unfortunately, it's quite difficult to "ignore" TS because the majority of projects uses typescript.

**Comment by atk** [comment] 2022-05-29 16:49
> Unfortunately, it's quite difficult to "ignore" TS because the majority of projects uses typescript.

It was not meant that we would like to actually ignore TS, but rather, "if it were not for this TS issue". We still use a lot of time and resources to improve the type definitions and documentation. Unfortunately, TS either forces us to ignore this TS issue or change our API to a less sensible one, something that we want to avoid.

**Comment by ryansolid** [comment] 2022-09-01 08:32
Closing as stale.

**Closed by ryansolid** 2022-09-01 08:32 UTC
Labels: typescript

**Comment by samuelstroschein** [comment] 2022-11-25 15:16
Discussion is ongoing in https://github.com/solidjs/solid/discussions/805
