### ISSUE TITLE
Possible hydration error causing double renders

### ISSUE THREAD

**Issue by ofarukaydin** [solidjs/solid#1952] opened 2023-11-11 16:54 UTC
### Describe the bug

This happens only with `renderStream`. It looks like hydration script inserts a new element instead of hydrating. You will see the element rendered twice instead of once.

### Your Example Website or App

https://stackblitz.com/~/github.com/ofarukaydin/solid-hydration-double

### Steps to Reproduce the Bug or Issue

1. Go to stackblitz
2. Refresh page
3. You will see the element rendered twice

### Expected behavior

I expect it to render only once

### Platform

- OS: Linux
- Browser: Chrome
- Version: 119

### Additional context

It works fine if you don't use control flow elements

```ts 
// Works fine
<Suspense fallback={"loading"}>
  <pre>
    <code>{JSON.stringify(query.data, null, 2)}</code>
  </pre>
</Suspense>

// The code below causes double rendering bug
<Suspense fallback={"loading"}>
    <Switch>
      <Match when={query.isError}>
        <div>{query.error?.message}</div>
      </Match>

      <Match when={!query.isFetching && !query.data}>
        <div>not found</div>
      </Match>

      <Match when={query.data}>
        <pre>
          <code>{JSON.stringify(query.data, null, 2)}</code>
        </pre>
      </Match>
    </Switch>
</Suspense>

**Comment by noobmaster19** [comment] 2023-11-12 04:02
I'm facing this issue as well.

**Comment by ryansolid** [comment] 2023-11-22 21:38
I'm so glad you reported this. This is caused by 1.8 new serialization. We were resolving the Suspense boundary before we were resolving the resources causing this weird timing glitch. I will get this fixed ASAP.

**Closed** 2023-11-22 22:51 UTC
Labels: bug
