### ISSUE TITLE
Spread operator props bug 1.6.0

### ISSUE THREAD

**Issue by Supertigerr** [solidjs/solid#1296] opened 2022-10-21 09:22 UTC
### Describe the bug

When using a function in the spread object as props, It does not seem to work. See example for a better understanding. This used to work fine before 1.6.0.

### Your Example Website or App

https://stackblitz.com/edit/github-2eplm3?file=package.json,dev%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Visit website
2. See that "This does not work?" Does not render.

### Expected behavior

"This does not work?" should render but it is not.

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: 1.6.0

**Comment by lxsmnsyc** [comment] 2022-10-21 09:59
It seems to be either a runtime or compiler bug, due to how `spread` doesn't reactively unwrap `props`. This is a bug

**Comment by ryansolid** [comment] 2022-10-21 16:47
Yeah this is a compiler bug thank you.

**Comment by russelgal** [comment] 2022-10-21 18:00
https://discord.com/channels/722131463138705510/817960620736380928/1033062692283498610
https://discord.com/channels/722131463138705510/722349143024205824/1032910707907366972
also does not work `mergeProps`

**Comment by ryansolid** [comment] 2022-10-21 18:24
> https://discord.com/channels/722131463138705510/817960620736380928/1033062692283498610 https://discord.com/channels/722131463138705510/722349143024205824/1032910707907366972 also does not work `mergeProps`

Those are other possible bugs/discussions.

@Supertigerr  For this problem I've reviewed isn't actually a bug. The Babel transformation is just out of date. Remove your package lock and reinstall and the issue goes away.

**Comment by Supertigerr** [comment] 2022-10-21 18:34
Ah alright. Just a question though. Isn't it bad to delete the package lock file? I remember reading on websites that you should never delete the package lock files.

**Comment by ryansolid** [comment] 2022-10-22 01:08
Maybe for control aspects. But I do it from time to time. Especially on any large update. Sometimes things will fill ranges and really you just want to update everything. There are other ways but I like the fresh install from time to time.

**Comment by lxsmnsyc** [comment] 2022-10-22 03:06
> Ah alright. Just a question though. Isn't it bad to delete the package lock file? I remember reading on websites that you should never delete the package lock files.

Delete it and run install again, it will be reconstructed.

**Comment by shishkin** [comment] 2022-10-23 11:19
I've stumbled upon a similar issue where spreading props breaks context propagation:

```tsx
const MyContext = createContext<Accessor<number>>();
const useMyContext = () => useContext(MyContext);

// it works if props not spread:
// function Host(props: {children: JSX.Element}) {
function Host({children}: {children: JSX.Element}) {
  const [count, setCount] = createSignal(10);
  return <MyContext.Provider value={count}>
    {children}
    <button type="button" onclick={() => setCount(c => c + 1)}>
      {count}
    </button>
  </MyContext.Provider>
}

function Counter() {
  const count = useMyContext();
  createEffect(() => console.log("Count:", count?.()));
  return (<p>{count}</p>);
}
```

See full example in [playground](https://playground.solidjs.com/?hash=-1868910517&version=1.4.1).

Also have this issue with all latest packages and purged lock file.

**Comment by ryansolid** [comment] 2022-10-23 11:39
Thats destructuring rest params which is slightly different than spreads. That will break context and lose reactivity. The one rule in Solid is don't destructure props.

**Comment by lxsmnsyc** [comment] 2022-10-23 11:39
You destructured props (which is semi-forbidden in Solid), specifically on `children`, which breaks propagation.

**Comment by KevinBLT** [comment] 2022-10-23 12:49
Something breaks `solid/meta-provider` for me, link tags don't have their attributes now:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/12692409/197393018-bd938aaa-daa7-40af-9c66-3a5e44758b85.png">

<img width="503" alt="image" src="https://user-images.githubusercontent.com/12692409/197393036-c12a4deb-122d-4d2d-b8a1-8f73965881fd.png">

Line 190 seems to be doing nothing as the result is:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/12692409/197393048-6f8ff39e-9a99-444d-b52c-42e4d7e40a87.png">

The link tags are empty.

**Comment by Schlumie** [comment] 2022-10-28 09:38
Can someone confirm that this bug relates to https://github.com/x64Bits/solid-icons/issues/15 and will be gone if this will be fixed ?

**Comment by ryansolid** [comment] 2022-10-28 16:59
The issue in Solid Meta was fixed a few days ago. For Solid Icons are they manually using spread calls in the code? This is one place there might be an issue, if using the internal `spread` calls. To my knowledge there is no bug in Solid around this, only that an internal function call signature changed. Unclear how much of the outer ecosystem was using this undocumented feature.

**Comment by ryansolid** [comment] 2022-10-30 07:10
Ok 1.6.1 fixed all the open issues we have reported with reproductions against spreads. Since the original issue wasn't actually an issue I'm going to close this one. And if you find issues against the new version please report them.

**Closed by ryansolid** 2022-10-30 07:10 UTC
