### ISSUE TITLE
reactivity lost when `npm link` nested solid-directories

### ISSUE THREAD

**Issue by bigmistqke** [solidjs/solid#1472] opened 2023-01-09 02:30 UTC
### Describe the bug

In the following project-directory-setup:
`
- root
  - package.json
  - src
    - Lib.tsx
  - dev
    - package.json 
    - src
      - Test.tsx
`

If I access component `Lib` from `Test.tsx` like `import Lib from "../src/Test"`, the props of `Lib` will not react on state-updates from `Test`, but only when I `vite build`. In dev-mode this set-up works.

I wanted a directory set-up like this, so that I could easily build an example-site for a solid-library.

### Your Example Website or App

https://github.com/bigmistqke/bug-report

### Steps to Reproduce the Bug or Issue

1. git clone https://github.com/bigmistqke/bug-report.git
2. root-directory and dev-directory: `npm install`
3. dev-directory: `npm run dev`
4. open browser: observe how there are two numbers counting up
5. dev-directory: `npm run build` & `npm run serve`
6. open browser: observe how there is only 1 number counting up

### Expected behavior

I expect there to be no difference between build and dev

### Screenshots or Videos

https://user-images.githubusercontent.com/10504064/211232854-aa4767be-b184-4847-ae95-b9c903a21ad3.mov

### Platform

- macOS
- firefox
- 108.0.2

**Comment by ryansolid** [comment] 2023-01-09 03:30
This sounds like bundling issue. My guess is that in dev mode it walks up to the nearest node module, but on build we are getting duplication somewhere. Like a version of Solid imported for each project. Be sure you are externalizing `solid-js` and `solid-js/web` for any build processes that involve libraries.

**Comment by bigmistqke** [comment] 2023-01-09 15:44
I updated the code to include `external: ["solid", "solid/web"]` in the rollup-config, but the problem still remains.

On further inspection, the problem also seems to occur when `npm link`ing... 

say if i have a directory
- lib
  - dist
  - src
- project
  - src

and I would do
1. lib: `npm link .`
2. project: `npm link lib` 
3. project: `npm run dev` :arrow_right: works
4. project: `npm run serve` :arrow_right: does not work

**Comment by izznatsir** [comment] 2023-01-10 02:52
The external should be `[ "solid-js", "solid-js/web" ]`. You missed the `-js`.

**Comment by bigmistqke** [comment] 2023-01-10 05:44
you are correct, but problem is still remaining with `[ "solid-js", "solid-js/web" ]`

**Comment by ryansolid** [comment] 2023-01-10 05:57
Well as suspected there are 2 copies of Solid in the build which is causing this. Let me see if I can track down why.

**Comment by ryansolid** [comment] 2023-01-10 06:07
Ok so best I got is this. Solid is installed in both root and nested. Unfortunately modules are resolved relative to their location. When you import `../../src` into your project it is resolving a different solid-js (the one in the root node_modules). Even if it is the same version. So each library ends up pulling in their own version. I confirmed this by deleting solid-js from the application's node modules and it worked. Since in this case the application would fail to find `solid-js` in the dev node_modules and fallback to the root. Why does this work in dev? Well Vite aggressively de-dupes in its optimization step..

**Comment by bigmistqke** [comment] 2023-01-10 06:14
so strange that it is bundled in the root-directory, since solid-js in the root-directory should be a peerDependency.
how do people nowadays do linked packages and stuff then in solid, since the problem is also occuring with `npm link`?

**Comment by bigmistqke** [comment] 2023-01-15 16:28
The `npm link` issue was caused by `npm link` itself. 

From [relative-deps](https://github.com/mweststrate/relative-deps) readme:
> These work only if there are no peer / shared dependencies involved. If there are shared dependencies, the linked library will resolve those in their own node_modules, instead of the node_modules of the hosting project, where it would normally be looked up. This results in peer dependencies ending up "twice" in the dependency tree, which often causes confusing behavior.

Tried out relative linking with this package instead and the double-library-issue vanished.

**Comment by ryansolid** [comment] 2023-01-15 21:17
Ok awesome. Thanks for following up. I'm going to close this now. But this was useful information to know.

**Closed** 2023-01-15 21:17 UTC

**Comment by tszyan** [comment] 2024-04-19 09:56
An alternative solution could be using resolve.dedupe. It seems cleaner to me. resolve.preserveSymlinks broke the @tiptap/* dependencies in my case.
