### ISSUE TITLE
When Google Translate is enabled on a website, SolidJS can't update some of the DOM

### ISSUE THREAD

**Issue by arnaud-cortisse** [solidjs/solid#1451] opened 2022-12-29 07:49 UTC
### Describe the bug

- I go on a Swedish website that uses SolidJS under the hood.
- I don't speak Swedish, so the built-in Google Translate feature of Chrome kicks in and translates the website I'm on. 
- As soon as the translation is enabled, some of the information on the page is off. 

### Your Example Website or App

https://playground.solidjs.com/anonymous/2c6ddc27-d592-4f8d-b3b4-eec01d4a5b12

### Steps to Reproduce the Bug or Issue

1. Go to https://playground.solidjs.com/anonymous/2c6ddc27-d592-4f8d-b3b4-eec01d4a5b12. 
2. Export the project as a .zip. 
3. Unzip the project. 
4. Go to the folder. 
5. `yarn`. 
6. `yarn start`.
7. Go to http://localhost:5173/ using Chrome. 
8. Observe the counters going up. 
9. Enable the Google Translate translation. 
10. Observe the counters stopping. 

### Expected behavior

As a user, I expect the website to keep working even with Google Translate enabled, but it's currently not the case. 

### Screenshots or Videos

![Dec-29-2022 08-37-34](https://user-images.githubusercontent.com/28689103/209919101-db710272-4247-4c4b-93db-07eb751f823a.gif)

DOM without Google Translate enabled:
<img width="396" alt="image" src="https://user-images.githubusercontent.com/28689103/209919686-6278f6bb-4586-4a4d-ba88-1936e45e5b8b.png">

DOM with Google Translate enabled:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/28689103/209919733-135a5840-8863-45c0-97cc-94252649c69c.png">

### Platform

- OS: macOS
- Browser: Chrome
- Version: Version 108.0.5359.124 (Official Build) (arm64)

### Additional context

I saw @ryansolid mentioned Google Translate messing things up here: https://github.com/solidjs/solid/issues/1122#issuecomment-1202115320.

**Comment by lxsmnsyc** [comment] 2022-12-29 08:07
It's most likely because Google Translate replaces the text nodes and Solid requires the node's position to apply updates. Once the translation happens, the text node is removed and Solid cannot append the new text node given that the original text node was missing.

**Comment by danieltroger** [comment] 2022-12-29 08:35
I thought that the issue was caused by solid not keeping a reference to the `Text` node but rather walking to it via `parent.ChildNodes` (see screenshot) but you are right, google translate also straight up _replaces_ the text node.

<img width="933" alt="Screenshot 2022-12-29 at 09 33 20" src="https://user-images.githubusercontent.com/4047180/209925165-fa80732c-d14c-4b52-a83b-3f1ffffea7dc.png">

I think one way to fix it would be to get google translate to use the same text node (and just replace the content) and solid to keep a reference to it?

**Comment by ryansolid** [comment] 2022-12-31 04:24
Yeah but will they do that? Other programs messing with the DOM is pretty problematic. The only thing we could do is check if the textNode has a parentNode before going into the optimization. Just trying to think if that falls down anywhere.

**Comment by ryansolid** [comment] 2022-12-31 05:57
Yeah React and countless other frameworks are waiting on issues like: https://bugs.chromium.org/p/chromium/issues/detail?id=872770

I'm long to close this one unfortunately as there is nothing to be done it looks like except hope Google does something here.

**Closed by ryansolid** 2022-12-31 05:57 UTC

**Comment by lxsmnsyc** [comment] 2022-12-31 08:24
TBF because text nodes are immutable (correct me if I'm wrong), this would just be deemed unfixable

**Comment by danieltroger** [comment] 2023-01-02 14:30
@ryansolid fair point. I think it would be good to meet google halfways and propose a middle ground that would work for both sides instead of putting it entirely on them (if you check the issue you linked someone claims the DOM is inherently mutable and it's 100% on "framework authors"). But it's hard to solve from solid's position. I proposed a way for google to solve it in their bug but there might be a better solution. Let's see how it goes.

@lxsmnsyc text nodes are not immutable, if you check the solid-js code in my screenshot above you can see that solid-js actually mutates them without creating new ones by changing https://developer.mozilla.org/en-US/docs/Web/API/CharacterData/data
