### ISSUE TITLE
`class` prop clobbers `classList` attribute on client render

### ISSUE THREAD

**Issue by samualtnorman** [solidjs/solid#1971] opened 2023-11-30 16:18 UTC
### Describe the bug

```jsx
const CoolButton = props => <button {...props} classList={{ foo: true, ...props.classList }}/>

export default () => <>
	<CoolButton>Foo</CoolButton>
	<CoolButton class="bar">Foo</CoolButton>
</>
```

The first button has the `foo` class (as expected).
The second button only has the `bar` class (unexpected).
This behavior does not match server render where everything works as expected.

### Your Example Website or App

https://playground.solidjs.com/anonymous/8ad21d6c-129e-4e99-8092-7adfb69ea8c6

### Steps to Reproduce the Bug or Issue

1. Visit the playground link.
2. Observe the preview.

### Expected behavior

Should match the behavior of server render where `classList` does not get clobbered.

### Screenshots or Videos

![image](https://github.com/solidjs/solid/assets/18307063/9d71fda9-7727-46cc-bd97-8ccb714ddd94)

### Platform

- OS: Linux
- Browser: Firefox
- Version: 120

### Additional context

Some things to note:
`class` and `classList` work as expected on server render.
It can be tricked into working properly with some extra spreading:
```jsx
const CoolButton = props => <button {...props} {...{ classList: { foo: true, ...props.classList } }}/>
```

**Comment by ryansolid** [comment] 2024-01-03 19:00
The problem is in `mergeProps` it is reversing the order of the properties so when the spread goes and processes them they are in reverse order. That being said ssr works because we try to merge class props, basically every element with spread de-opts to every property treated as part of the spread. This is maybe something worth considering in the future but I'd rather just have the merged props added in the correct order internally for now.

**Comment by ryansolid** [comment] 2024-01-08 22:22
I'm starting to think we may have overcomplicated the non-proxy case early on. Like before we split into both cases we used to try handle much more complicated structures.

Like consider:
```js
const props = {
  get value() {
    return value1()
  }
}

const something = {
  get value() {
    return value2();
  }
}

<Comp {...props} value={something.value} />
```
If neither of these are stores should undefined value fall through? Ie..  if `value2()` is undefined should we get `value1()`?

The argument for this for proxies is clear as objects can change shape and we unfortunately don't clean up keys.  But this cannot change shape. If you are overriding value here that is precisely what you intend to do. I think we need to do a breaking change in `mergeProps`. But this is too big to do immediately and makes sense in 2.0.

I will fix the order for 1.x but I fear there maybe a bit of overhead to do so.

**Closed** 2024-01-08 22:24 UTC
Labels: bug
