### ISSUE TITLE
<For each={task_list}></For> could not refresh the data

### ISSUE THREAD

**Issue by hhao99** [solidjs/solid#986] opened 2022-05-16 04:19 UTC
### Describe the bug

in the code snippet:

const [tasks, setTasks] = createStore([])

we use the solidjs For to iterate the list:
<For each={tasks}>{ task => <h3>{task.text}</h3>} </For>
in the same files , the task list was refresh very well when the state updated,
but we split the code in the seperate file, this code was not refresh the UI.

so we switch to classis array.map to show the tasks, it is ok in the seperate file:
{ tasks.map( task=> <h3>{task.text}</h3> }

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

n/a

### Expected behavior

as a user, we expect the For loop can refresh the state in the seperate file.

### Platform

- OS: [osx 11.6]
- Browser: [ Chrome]
- Version: [101]

**Comment by atk** [comment] 2022-05-16 06:10
If you put the state outside of a component, you need to wrap it in a createRoot in order to make them reactive.

**Comment by ryansolid** [comment] 2022-05-16 06:13
Probably need a reproduction because we are just guessing at this point.

**Comment by martpie** [comment] 2022-06-01 13:05
I believe I am facing something similar. I'm creating a store in a separate file, but it is not created within any context/root, it's just a standalone file. So reactivity only works when "hard-reloading" the component for example (moving to another route then come back).

It's probably a bad habit I have coming from React/Redux, but from my understanding, `createStore` and reactive variables in general need to be created within a `root` right?

So it wouldn't really be possible to `import {store, setStore} from './my-store'`. I would need to access this store via a context if I understand correctly.

**Comment by ryansolid** [comment] 2022-06-01 16:57
Yeah it can be created outside without a root. I imagine the problem is something else.

Example: https://playground.solidjs.com/?hash=-529548877&version=1.4.1

**Comment by martpie** [comment] 2022-06-01 21:34
Yes indeed, I was passing a store property down the tree of components via props and was expecting it to trigger updates automatically.

**Comment by martpie** [comment] 2022-06-02 09:22
Ok, for everyone coming after me, DO NOT DESTRUCTURE YOUR PROPS in your component function body (and I suspected something similar happened to OP)

Don't:

```tsx
const Display = (props) => {
  const { items } = props; // reactivity is lost here

  return <div>{items.join(', ')}</div>;
}
```

Do:

```tsx
const Display = (props) => {
  return <div>{props.items.join(', ')}</div>;
}
```

I browsed a little bit the issues/discussions and it would appear it's a very common issue (especially when coming from React). I wonder if an ESLint plugin could prevent developers from shooting themselves in the foot with this kind of small gotchas.

**Comment by LXSMNSYC** [comment] 2022-06-02 10:13
If you're coming from React, this is a common issue, but it's a two-way issue really (both the user and the docs). The docs mentions how Solid components only ever evaluate once (which is unlike React) which we expect users to understand, but the concept of reactivity in props isn't something users understand in a glimpse.

**Comment by ryansolid** [comment] 2022-06-02 23:01
Yeah I think this one has run its course if there are no other updates. Original poster can reopen if there is still a bug.

**Closed by ryansolid** 2022-06-02 23:01 UTC
Labels: unverified bug
