### ISSUE TITLE
Function of createMemo is called twice when depends on resource

### ISSUE THREAD

**Issue by unoexperto** [solidjs/solid#2260] opened 2024-08-20 20:18 UTC
### Describe the bug

Hi folks,

My apologies if it should be in discussions.  The problem is that function of createMemo is called twice when depends on resource. In the first call the resource.state is 'pending'.

### Your Example Website or App

https://stackblitz.com/

### Steps to Reproduce the Bug or Issue

I have a page with roughly following code

```ts
export default function MyView() {

  const context = useContext(SessionContext);
  const params = useParams()
  const [myObject] = createResource(() => Number(params.id), async (myObjId) => {
    return await api.getMyObject(myObjId);
  })

  let srcPlugin = createMemo(() => {
    const sourceId = myObject()?.sourceId;
    console.log(`++++++++ myObject ID: ${params.id} _ ${myObject()?.id} * ${sourceId}`)
    return sourceId !== undefined ? context.sourcePlugins?.get(sourceId) : undefined;
  })

  return (
      <Show when={myObject()} fallback={<LoadingIcon/>}>
            <Show when={srcPlugin()} fallback={<LoadingIcon/>}>
              {srcPlugin()?.name}
            </Show>
      </Show>
  );
}
```

### Expected behavior

My expectation is that createMemo's function is never called until resource is fully initialized. But instead it's called twice. I discovered this issue when I realized that outer `Show` against the resource is not sufficient and I have to re-check memo variable too. Ironically I don't have this problem if srcPlugin is dumb function that uses resource.

Is it by design?

### Platform

- OS: Linux
- Browser: Chrome
- Version:1.8.21

**Comment by ryansolid** [comment] 2024-08-20 22:59
Memo's aren't lazy in solid so they will run eagerly. Once immediately on declaration and once when it completes. To be fair even if they were lazy they would get called twice anyway, as soon as they were read somewhere.

The only way to avoid running it twice is if the resource threw like React.. which we don't do currently but is something we are looking into for the future.

That being said a dumb function would be called twice too. Immediately when read in the Show, and later when the resource resolved. So maybe I'm missing something?

**Comment by unoexperto** [comment] 2024-08-21 08:54
Thank you for the quick response, Ryan. I didn't expect that :) 

I guess what feels counter-intuitive to me is that

1) I expected the memo to be computed eagerly, and I'm ok with it being called twice (hence I added the `sourceId !== undefined` check), **but** 

2) because I have `<Show when={myObject.state === "ready"}>`, which means `myObject.state == "ready"`, Solid must have calculated the second memo value before trying to render the inner element with the older memo. 

So I was thinking, "How come the memo value inside the `myObject.state = "ready"` Show is stale if Solid could not have avoided computing the memo again after the resource became ready?" It's like having an if statement in the code whose condition is ignored in some cases.

---

As per dumb reactive function, it's called in every use of it but it's never called before resource is ready. For the sake of example following code caches the value and at the same time avoids propagating event for incomplete resource:

```typescript
function myMemo<In, Out>(src: () => In | undefined, compute: (input: In | undefined) => Out | undefined) {

  let lastInput: In | undefined = undefined;
  let lastOutput: Out | undefined = undefined;

  return () => {

    const newInput = src();
    if (newInput !== lastInput) {
      lastInput = newInput
      lastOutput = compute(newInput);
    }

    return lastOutput;
  }
}

let srcPlugin = myMemo(() => myObject()?.sourceId, input => context.sourcePlugins?.get(input))
```

What would be great is to be able to create derived signal in Solid that has ability to emit nothing. So using Project Reactor as an example it might look like this:

```kotlin
import reactor.core.publisher.Flux

enum class State {
    Pending,
    Ready
}

interface Resource<T> {
    val state: State
    val value: T
}
interface MyObject {
    val sourceId: String
}

interface Plugin {
    
}

fun main (args : Array<String>) {
    
    val plugins: Map<String, Plugin> =
    val resource: Flux<Resource<MyObject>> = ... emits new value when resource changes
    val deriveSignal: Flux<Plugin> = resource
                                                                .filter { it.state == State.Ready }
                                                                .mapNotNull { plugins[it.value.sourceId] }
}
```

Does it make sense ?

**Comment by ryansolid** [comment] 2024-08-21 16:12
Yeah it's because of the eager evaluation. I was mistaken before (not noticing the outer Show), the function would only run once because it is evaluated lazily because of the outer Show. The Memo runs regardless of whether it is used or not. This is something we are re-examining in 2.0(if you are interested read [this series](https://dev.to/this-is-learning/derivations-in-reactivity-4fo1)), but in 1.0 all computations are queued and run eagerly. But if I understand the flow what is happening is:

1. We hit the declarations of both the resource and the memo and they are run immediately.
2. We hit the outer Show component that reads and see undefined and short circuits.
3. Resource resolves, and pure part of calculations run, so memo re-runs, and then Show re-runs
4. Finally new Show is there and reads the value and shows its children.

In the case of the function instead of the memo:

1. We hit the declarations of both the resource and the function but only the resource is run immediately.
2. We hit the outer Show component that reads and see undefined and short circuits.
3. Resource resolves, and pure part of calculations so the Show re-runs
4. New Show runs and runs our function for the first time, showing the children

The current reactive system is oblivious to async. It was something tagged on top and basically doesn't propagate through the graph but because of our eager scheduling it doesn't really matter anyway. While Solid is push/pull it is one of the older systems in JS, based on work done back in ~2012 time period with S.js. It's more like 80% push and then pull as needed. Our memo's do guard against downstream notification/execution but it isn't the sinks that decide if things are run.

There is a `createLazy` memo in Solid primtives that hacks around our reactive system to make it work (https://primitives.solidjs.community/package/memo#createLazyMemo). This isn't core behavior today but something at the top of the list of our 2.0 work.

**Comment by ryansolid** [comment] 2024-08-22 20:31
It sounds like this is by design currently which means I will close this. But I'm glad to have the feedback to know we are working in the right direction for the future.

**Closed by ryansolid** 2024-08-22 20:31 UTC

**Comment by unoexperto** [comment] 2024-08-23 09:49
@ryansolid Thank you, Ryan. Speaking of Solid 2.0. I saw in one of your streams you have 2.0 notes. Is there link where I can follow/read those notes? Also is there branch with 2.0 work? I'm happy to try it and contribute.

**Comment by ryansolid** [comment] 2024-08-23 15:16
I haven't brought it altogether yet. I have a branch in dom-expressions with the updated compiler and I'm working on the new reactivity. When it gets a little bit further I intend to start the effort under the next branch in this repo.
