### ISSUE TITLE
Video HTML tag shows black screen in iOS safari

### ISSUE THREAD

**Issue by stereobooster** [solidjs/solid#1408] opened 2022-12-09 16:22 UTC
### Describe the bug

with solidjs video shows black screen when I try to stream video from camera. See readme here https://github.com/stereobooster/solidjs-ios-video-bug for details

### Your Example Website or App

https://github.com/stereobooster/solidjs-ios-video-bug

### Steps to Reproduce the Bug or Issue

1. Open this URL https://solidjs-ios-video-bug.netlify.app/ in iOS Safari
2. Click on rectangle with red broder
3. You would see black rectangle

### Expected behavior

1. You would see video instead of black rectangles

### Screenshots or Videos

![](https://github.com/stereobooster/solidjs-ios-video-bug/raw/main/screenshot.jpeg)

### Platform

- OS: iOS14
- Browser: Safari
- Version: ...

**Comment by atk** [comment] 2022-12-09 20:23
Can you try some more idiomatic code?

```js
import { createSignal } from "solid-js";

export default function Home() {
  const [source, setSource] = createSignal();
  const getStream = () => navigator.mediaDevices.getUserMedia({
    audio: false,
    video: { facingMode: "environment" },
  }).then(setSource).catch(alert);

  return (
    <main>
      <Title>Video bug</Title>
      <video
        style={{border: "1px solid red"}}
        prop:srcObject={source()}
        autoplay
        muted
        playsinline
        onClick={getStream}
      />
    </main>
  );
}
```

**Comment by stereobooster** [comment] 2022-12-09 22:26
Same result. I've tried a lot of variations. Code was written this way to be as close as possible to baseline

**Comment by ryansolid** [comment] 2022-12-12 19:59
Hmm.. this reminds me of a bug we had a while ago where the browser wasn't handling cloned elements properly. I can't locate it, but I needed to open an issue with the browser for it. Without having an ios device it might be harder to track down.

Most likely culprit is Solid initializes elements via element.cloneNode. We probably want to compare direct creation `document.createElement` vs cloning that element to see if that is the culprit. Then we can at least follow up with the browser.

**Comment by patdx** [comment] 2023-02-07 10:14
Hi, out of curiosity I tried the link https://solidjs-ios-video-bug.netlify.app/ on iPhone 12 with iOS 16.2 (latest OS version at time of writing) and I got a real video feed.

**Comment by ryansolid** [comment] 2023-03-10 04:57
Yeah... this feels like that bug. @stereobooster can you confirm you still reproduce this on newer versions of iOS. This may just be an older bug they already fixed.

**Comment by BelkinVadim** [comment] 2023-03-28 14:28
it turns out for iOS 14 there is no solution to the problem?

**Comment by ryansolid** [comment] 2023-03-30 04:15
Not sure. The original issue for Mac OS they fixed in a patch version. So I'd expect if this is related it would be fixed in a later version of 14. But not sure if this is related or just the same symptoms.

**Comment by ryansolid** [comment] 2023-06-26 22:40
Closing as stale. Reopen if needed.

**Closed by ryansolid** 2023-06-26 22:40 UTC
Labels: unverified bug

**Comment by linkthai** [comment] 2024-11-25 08:37
Can confirm this problem exists on even the latest version iOS 14. I bandaged it by creating `<video/>` programmatically instead.

```ts
import { onMount } from 'solid-js';
import { useScan } from './ScanContext';
import './scan.scss';

export function ScanVideo() {
  const { initScan } = useScan();

  onMount(async () => {
    const videoWrapper = document.getElementById('video-wrapper');
    if (videoWrapper) {
      const videoElement = document.createElement('video');
      videoElement.id = 'scanner';
      videoElement.className = `w-full h-full`;
      videoElement.muted = true;
      videoElement.setAttribute('playsinline', '');
      videoElement.setAttribute('webkit-playsinline', '');
      videoElement.poster = 'none';
      videoWrapper.appendChild(videoElement);

      initScan(videoElement);
    }
  });

  return <div id="video-wrapper" class="h-full w-full"></div>;
}

```
