### ISSUE TITLE
v1.8.1 does not build on skypack

### ISSUE THREAD

**Issue by vezwork** [solidjs/solid#1921] opened 2023-10-16 18:43 UTC
### Describe the bug

skypack fails to build v1.8.1: https://cdn.skypack.dev/solid-js/web
```
/*
 * [Package Error] "solid-js@v1.8.1" could not be built. 
 *
 *   [1/5] Verifying package is valid…
 *   [2/5] Installing dependencies from npm…
 *   No matching version found for solid-js@1.8.1.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"solid-js@v1.8.1\" could not be built. \n[1/5] Verifying package is valid…\n[2/5] Installing dependencies from npm…\nNo matching version found for solid-js@1.8.1.");
throw new Error("[Package Error] \"solid-js@v1.8.1\" could not be built. ");
export default null;
```

### Your Example Website or App

https://cdn.skypack.dev/solid-js/web

### Steps to Reproduce the Bug or Issue

1. Just navigate to https://cdn.skypack.dev/solid-js/web

### Expected behavior

v1.8 should build

### Platform

Not sure what skypack uses.

### Additional context

it also previously failed to build in v1.7, but was fixed: https://github.com/solidjs/solid/issues/1660

[jsdelivr](https://www.jsdelivr.com/package/npm/solid-js?tab=files&path=html%2Fdist) works for the main library but I cannot find a way to get it to work for `/web` or `/html`.

As a result, I do not know a way to run solidjs from a CDN. All solidjs pens on codepen seem to be broken (except one that imports an older version).

**Comment by ryansolid** [comment] 2023-10-17 15:41
Yeah this one is mystifying as the code looks like valid JS. In 1.7 it was a very non-sensical fix that just by chance happened to fix it. Although it is pretty clear the issue is with `/web` so there is something here.

**Comment by ryansolid** [comment] 2023-10-18 07:19
I asked Fred and he told me Skypack is all but dead. So no help there. The recommended CDN now is: https://esm.sh/solid-js@1.8.1. It supports submodules via URLs like: https://esm.sh/solid-js@1.8.1/web.

I will leave this around for a while if people want to try to speculate what is causing this but it probably isn't the best use of time.

**Comment by birkskyum** [comment] 2023-10-18 09:51
@vezwork  -  https://status.skypack.dev/

**Comment by vezwork** [comment] 2023-10-18 19:58
Thank you @ryansolid! I was successfully able to get the starter counter app working with esm.sh using its submodule support. 

I was attempting to use skypack because it is what the [getting started buildless](https://www.solidjs.com/guides/getting-started#buildless-options) options part of the solid js docs uses. I'm going to go put up a PR to change skypack to esm.sh there and I'll link it here once I have.

**Comment by vezwork** [comment] 2023-10-18 20:11
Here is a PR to replace skypack usage with esm.sh usage in the getting started -- buildless options part of the docs: https://github.com/solidjs/solid-docs/pull/275

**Comment by birkskyum** [comment] 2023-10-19 08:36
With skypack down, with no prospect of getting up again, I guess this can be closed.

**Comment by ryansolid** [comment] 2023-10-19 17:50
Docs update has been merged. I'm going to close this. Thank you everyone involved.

**Closed by ryansolid** 2023-10-19 17:50 UTC
Labels: bug, wontfix
