### ISSUE TITLE
Issues with `classList` when used with reactive class

### ISSUE THREAD

**Issue by otonashixav** [solidjs/solid#751] opened 2021-12-03 13:06 UTC
**Describe the bug**
`classList` has various issues when used together with a reactive `class`. See the reproduction for some examples. 

**To Reproduce**
See reproduction; the buttons should start and remain red when clicked.

**Expected behavior**
Classes from `classList` should be applied and not overwritten when `class` changes. 

**Reproduction**
[Playground Link](https://playground.solidjs.com/?hash=1175164409&version=1.2.5)

**Comment by ryansolid** [comment] 2021-12-03 17:07
Open to suggestions on what you think the behavior is. This is the problem with having 2 things I guess. But `class` is literally set the className and `classList` is toggle. I don't see us fixing this without changing the behavior of `class`. Which I'm not sure makes a lot of sense. A compiler analysis could get us some of the way but then you have things like spreads to deal with. I'm much more on the side of you probably don't want to mix these for dynamic. The real answer might be directionally going to merge them or move classList into a `use:` hook or something so people wouldn't expect different behavior.

Thoughts?

**Comment by otonashixav** [comment] 2021-12-03 17:42
I was hoping for it to just work somehow, but it's fine as is if the behaviour and workarounds (I guess classList with `[props.class]: true` is the simplest) are documented. Most of the examples shown aren't really something you'd encounter normally; I ran into the first one when trying to merge `props.class` and use a spread at the same time i.e. this:
```jsx
<div class={props.class + ' some-other-class'} {...otherProps} />
```
causing the classList to be ignored even though `props.class` is intended to be static (so basically solvable by accessing it outside the jsx).

**Comment by ryansolid** [comment] 2021-12-03 17:53
Yeah I just don't have a great solution other than maybe making our `class` attribute more powerful. It's just tricky because in non-analyzable scenarios requires always pulling in the classList code. I mean it's not hard to identify. One's a string and the other is an object but just food for thought. Maybe someone else has a preference or thoughts.

**Comment by ryansolid** [comment] 2021-12-03 23:05
Ok I'm going to close this one by design but open a new issue on dom-expressions to explore this. https://github.com/ryansolid/dom-expressions/issues/98

**Closed by ryansolid** 2021-12-03 23:05 UTC
Labels: enhancement
